---
version: '3.3'

services:

  activemq:
    image: rmohr/activemq:5.15.6-alpine
    container_name: activemq
    hostname: activemq
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672
      - 61613:61613
      - 1883:1883
      - 61614:61614
